# <center> Лабораторна робота Numpy
# <center> Виконав: студент групи ПБ-21 мп Якобчук Євгеній

# Початок роботи з бібліотекою Numpy

У даній лабораторній роботі розглянуто наступний функціонал бібліотеки Numpy:
1. Створення масиву.
2. Відображення масивів .
3. Базові операції з масивами.

## Імпорт бібліотек та пакетів

Завантажуємо бібліотеку numpy та використаємо скорочення np.

In [1]:
import numpy as np

# Завдання
## 1. Створити двомірний нульовий масив розміром 11х11 та заповнити його діагоналі одиницями.

1.1. Задати розмір масиву

In [2]:
size = (11,11)

1.2. Створити нульовий масив заданого розміру

In [3]:
arr = np.zeros(size)

1.3 Надрукувати створений масив

In [4]:
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


1.4 Змінити діагоналі за допомогою двох циклів

In [5]:
for i in range(11):
	for j in range(11):
		if (i==j):
			arr[i][j] = 1
		elif (i+j == 10):
			arr[i][j] = 1

1.5 Вивести створений масив

In [6]:
print(arr)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


## 2. Засобами NumPy створити вертикальні та горизонтальні зображення градієнту в обидва боки (поступове збільшення яскравості на зображенні).

Приклад зображення градієнту
<img src="./assignments/horizontal_grad.jpg" height="200" width="200">

### Горизонтальний градієнт

2.1 Створити нульовий масив розміром 255х255

In [7]:
horizontal_gradient1 =np.zeros([255,255])
print(horizontal_gradient1)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


2.2 Визначити розміри масиву

In [8]:
w = horizontal_gradient1.shape[1]
h = horizontal_gradient1.shape[0]

2.3 Поелементно змінити яскравості кожного пікселя

In [9]:
for i in range(w):
    for j in range(h):
        horizontal_gradient1[i][j] = horizontal_gradient1[i][j]+j
horizontal_gradient1

array([[  0.,   1.,   2., ..., 252., 253., 254.],
       [  0.,   1.,   2., ..., 252., 253., 254.],
       [  0.,   1.,   2., ..., 252., 253., 254.],
       ...,
       [  0.,   1.,   2., ..., 252., 253., 254.],
       [  0.,   1.,   2., ..., 252., 253., 254.],
       [  0.,   1.,   2., ..., 252., 253., 254.]])

2.4 Записати зображення засабами OpenCV

In [10]:
import cv2
cv2.imwrite('horizontal_grad1.jpg', horizontal_gradient1)

True

2.5 Аналогічно створити горизонтальний градієнт в інший бік

In [11]:
horizontal_gradient2 = np.zeros([255,255])
w = horizontal_gradient2.shape[1]
h = horizontal_gradient2.shape[0]
for i in range(w):
    for j in range(h):
        horizontal_gradient2[-i][-j] = horizontal_gradient2[-i][-j]+j   
cv2.imwrite('horizontal_grad2.jpg', horizontal_gradient2)
horizontal_gradient2

array([[  0., 254., 253., ...,   3.,   2.,   1.],
       [  0., 254., 253., ...,   3.,   2.,   1.],
       [  0., 254., 253., ...,   3.,   2.,   1.],
       ...,
       [  0., 254., 253., ...,   3.,   2.,   1.],
       [  0., 254., 253., ...,   3.,   2.,   1.],
       [  0., 254., 253., ...,   3.,   2.,   1.]])

### Вертикальний градієнт

2.6 Створити нульовий масив розміром 255х255

In [12]:
vertical_gradient1 = np.zeros([255,255])

2.7 Визначити розміри масиву

In [13]:
w = vertical_gradient1.shape[1]
h = vertical_gradient1.shape[0]

2.8 Поелементно змінити яскравості кожного пікселя

In [14]:
for i in range(w):
    for j in range(h):
        vertical_gradient1[j][i] = vertical_gradient1[j][i]+j

2.9 Записати зображення засабами OpenCV

In [15]:
cv2.imwrite('vertical_grad1.jpg', vertical_gradient1)

True

2.10 Аналогічно створити горизонтальний градієнт в інший бік

In [16]:
vertical_gradient2 = np.zeros([255,255])

w = vertical_gradient2.shape[1]
h = vertical_gradient2.shape[0]

for i in range(w):
    for j in range(h):
        vertical_gradient2[-j][-i] = vertical_gradient2[-j][-i]+j
        
cv2.imwrite('vertical_grad2.jpg', vertical_gradient2)


True